Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CafeteriaOnline.Website.Data;
using CafeteriaOnline.Website.Models;
using Microsoft.AspNetCore.Authorization;

namespace CafeteriaOnline.Website.Controllers
{
    [Authorize(Roles = "Caterer")]
    public class MealsController : Controller
    {
        private readonly CafeteriaContext _context;

        public MealsController(CafeteriaContext context)
        {
            _context = context;
        }

        // GET: Meals
        public async Task<IActionResult> Index()
        {
            var cafeteriaContext = _context.Meals.Include(m => m.Caterer);
            return View(await cafeteriaContext.ToListAsync());
        }

        // GET: Meals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals
                .Include(m => m.Caterer)
                .FirstOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // GET: Meals/Create
        public IActionResult Create()
        {
            ViewData["CatererId"] = new SelectList(_context.Caterers, "Id", "Id");
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MealId,Name,MealType,Description,ValidUntil,ImageUrl,CatererId")] Meal meal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatererId"] = new SelectList(_context.Caterers, "Id", "Id", meal.CatererId);
            return View(meal);
        }

        // GET: Meals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals.FindAsync(id);
            if (meal == null)
            {
                return NotFound();
            }
            ViewData["CatererId"] = new SelectList(_context.Caterers, "Id", "Id", meal.CatererId);
            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MealId,Name,MealType,Description,ValidUntil,ImageUrl,CatererId")] Meal meal)
        {
            if (id != meal.MealId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MealExists(meal.MealId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatererId"] = new SelectList(_context.Caterers, "Id", "Id", meal.CatererId);
            return View(meal);
        }

        // GET: Meals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meal = await _context.Meals
                .Include(m => m.Caterer)
                .FirstOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return NotFound();
            }

            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meal = await _context.Meals.FindAsync(id);
            _context.Meals.Remove(meal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MealExists(int id)
        {
            return _context.Meals.Any(e => e.MealId == id);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CafeteriaOnline.Website.Data;
using CafeteriaOnline.Website.Models;
using Microsoft.AspNetCore.Authorization;

namespace CafeteriaOnline.Website.Controllers
{
    [Authorize(Roles = "Caterer,Cashier")]
    public class OrdersController : Controller
    {
        private readonly CafeteriaContext _context;

        public OrdersController(CafeteriaContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var cafeteriaContext = _context.Orders.Include(o => o.Employee);
            return View(await cafeteriaContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,EmployeeId,OrderDate,ModifiedDate,ForDate,PaidStatus,OrderStatus")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", order.EmployeeId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,EmployeeId,OrderDate,ModifiedDate,ForDate,PaidStatus,OrderStatus")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", order.EmployeeId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Employee)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CafeteriaOnline.Website.Data;
using CafeteriaOnline.Website.Models;
using Microsoft.AspNetCore.Authorization;
using CafeteriaOnline.Website.Helpers;
using Microsoft.AspNetCore.Identity;

namespace CafeteriaOnline.Website.Controllers
{
    [Authorize(Roles = "Employee,Organizer")]
    public class ShopController : Controller
    {
        private readonly CafeteriaContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ShopController(CafeteriaContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Shop
        public async Task<IActionResult> Index()
        {
            DateTime localDate = DateTime.Today;

            var cart = GetCart();
            ViewBag.cart = cart;
            ViewBag.meals = await _context.Meals.Include(item => item.MealConfigurations).Where(item => item.ValidUntil.Date > localDate).ToListAsync();
            ViewBag.count = cart.Sum(item => item.Quantity);
            return View();
        }

        public IActionResult Cart()
        {
            var cart = GetCart();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.MealConfiguration.Price * item.Quantity);
            return View();
        }

        public IActionResult OrderThankYou()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cart([Bind("ForDate")] Order order)
        {
            var cart = GetCart();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.MealConfiguration.Price * item.Quantity);
            DateTime localDate = DateTime.Now.Date;
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("ForDate", "Please enter a date");
                return View();
            }
            else if ((order.ForDate.Date - localDate).TotalDays < 3)
            {
                // make sure it is at least one day ahead
                ModelState.AddModelError("ForDate", "Date must be 3 days in advance");
                return View();
            }
            else if (cart.ToList().Count < 1)
            {
                ModelState.AddModelError("ForDate", "Please add Items to your cart");
                return View();
            }

            var user = await _userManager.GetUserAsync(HttpContext.User);
            if (user != null)
            {
                List<OrderItem> orderItems = new List<OrderItem>();
                for (int i = 0; i < cart.ToList().Count; i++)
                {
                    // make sure the item will still be valid on the date it is ordered
                    if (DateTime.Compare(cart[i].MealConfiguration.Meal.ValidUntil.Date, order.ForDate.Date) < 0)
                    {
                        ModelState.AddModelError("ForDate", "Cart items must be valid on the ForDate " + cart[i].MealConfiguration.Meal.Name.ToString());
                        return View();
                    }
                    OrderItem orderItem = new OrderItem
                    {
                        Quantity = cart[i].Quantity,
                        MealConfigurationId = cart[i].MealConfiguration.MealConfigurationId
                    };
                    orderItems.Add(orderItem);
                }

                Order newOrder = new Order
                {
                    EmployeeId = user.Id,
                    OrderDate = localDate.Date,
                    ModifiedDate = localDate,
                    ForDate = order.ForDate.Date,
                    PaidStatus = PaidStatus.Unpaid,
                    OrderStatus = OrderStatus.Pending,
                    OrderItems = orderItems,
                };
                _context.Add(newOrder);
                await _context.SaveChangesAsync();

                // clear cart
                SessionHelper.Set(HttpContext.Session, "cart", new List<OrderItem>());
            }
            return RedirectToAction("OrderThankYou");
        }

        public async Task<IActionResult> Add(int id)
        {
            var result = await AddItemToCart(id);
            if (!result)
            {
                return NotFound();
            }

            return RedirectToAction("Cart");
        }

        public async Task<IActionResult> AddItem(int id)
        {
            var result = await AddItemToCart(id);

            if (!result)
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        public async Task<bool> AddItemToCart(int id)
        {

            List<OrderItem> cart = GetCart();

            var mealConfiguration = await _context.MealConfigurations.Include(n => n.Meal).SingleOrDefaultAsync(i => i.MealConfigurationId == id);
            if (mealConfiguration == null)
            {
                return false;
            }
            var index = cart.FindIndex(item => item.MealConfiguration.MealConfigurationId == id);

            if (index == -1)
            {
                cart.Add(new OrderItem { MealConfiguration = mealConfiguration, Quantity = 1 });
            }
            else
            {
                if (cart[index].Quantity < 25)
                    cart[index].Quantity++;
            }
            SessionHelper.Set(HttpContext.Session, "cart", cart);

            return true;
        }

        public IActionResult Remove(int id)
        {
            List<OrderItem> cart = GetCart();

            var index = cart.FindIndex(item => item.MealConfiguration.MealConfigurationId == id);
            if (index != -1)
            {
                if (cart[index].Quantity > 1)
                    cart[index].Quantity--;
                else
                    cart.RemoveAt(index);
            }
            SessionHelper.Set(HttpContext.Session, "cart", cart);
            return RedirectToAction("Cart");
        }

        public IActionResult Delete(int id)
        {
            List<OrderItem> cart = GetCart();

            var index = cart.FindIndex(item => item.MealConfiguration.MealConfigurationId == id);
            if (index != -1)
            {
                cart.RemoveAt(index);
            }
            SessionHelper.Set(HttpContext.Session, "cart", cart);
            return RedirectToAction("Cart");
        }

        private List<OrderItem> GetCart()
        {
            List<OrderItem> cart = new List<OrderItem>();
            if (SessionHelper.Get<List<OrderItem>>(HttpContext.Session, "cart") != default)
            {
                cart = SessionHelper.Get<List<OrderItem>>(HttpContext.Session, "cart");
            }
            return cart;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CafeteriaOnline.Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://unpkg.com/tailwindcss@1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-orange-500 border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Online Cafeteria System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Caterer") || User.IsInRole("Cashier"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="">Orders</a>
                            </li>
                        }
                        @if (User.IsInRole("Caterer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Meals" asp-action="">Meals</a>
                            </li>
                        }
                        @if (User.IsInRole("Caterer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MealConfigurations" asp-action="">MealConfigurations</a>
                            </li>
                        }
                        @if (User.IsInRole("Caterer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Companies" asp-action="">Companies</a>
                            </li>
                        }
                        @if (User.IsInRole("Caterer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CafeteriaFoods" asp-action="">CafeteriaFoods</a>
                            </li>
                        }
                        @if (User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserOrders" asp-action="">Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="">Shop</a>
                            </li>
                        }
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CafeteriaOnline.Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>